name = "go-nitro"
[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true

[builders."exec:go"]
enabled = true

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:swarm"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name= "create-ledger"
instances = { min = 2, max = 100, default = 5 }


[[testcases]]
name= "create-virtual"
instances = { min = 2, max = 100, default = 5 }

    [testcases.params]
    numOfChannels =  { type = "int", default = 2 } 
    numOfHubs = {type ="int", default = 1}