name = "go-nitro-testground"
[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
build_base_image = "golang:1.19-buster"
enabled = true
[builders."docker:go".dockerfile_extensions]
post_runtime_copy = "COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt"
pre_source_copy = "RUN update-ca-certificates --verbose"

[builders."exec:go"]
enabled = true

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:swarm"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
instances = {min = 2, max = 100, default = 5}
name = "virtual-payment"

[testcases.params]
concurrentPaymentJobs = {type = "int", desc = "The number of concurrent payment jobs a peer should attempt to maintain", default = 1}
isCI = {type = "bool", default = false, desc = "Whether this test is being run as from CI"}
isNightly = {type = "bool", default = false, desc = "Whether this test is being run as part of the nightly test suite"}
networkJitter = {type = "int", unit = "milliseconds", default = 0}
networkLatency = {type = "int", unit = "milliseconds", default = 0}
numOfHubs = {type = "int", default = 1, desc = "The number of instances that should play the role of the hub"}
numOfIntermediaries = {type = "int", default = 1, desc = "The number of intermediaries(hops) to use in the virtual payment channel"}
numOfPayeePayers = {type = "int", default = 0, desc = "The number of instances that should play the role of the payeepayer"}
numOfPayees = {type = "int", default = 1, desc = "The number of instances that should play the role of the payee"}
numOfPayers = {type = "int", default = 1, desc = "The number of instances that should play the role of the payer"}
paymentTestDuration = {type = "int", default = 10, unit = "seconds"}

[[testcases]]
instances = {min = 2, max = 100, default = 5}
name = "fevm-virtual-payment"

[testcases.params]
concurrentPaymentJobs = {type = "int", desc = "The number of concurrent payment jobs a peer should attempt to maintain", default = 1}
isCI = {type = "bool", default = false, desc = "Whether this test is being run as from CI"}
isNightly = {type = "bool", default = false, desc = "Whether this test is being run as part of the nightly test suite"}
networkJitter = {type = "int", unit = "milliseconds", default = 0}
networkLatency = {type = "int", unit = "milliseconds", default = 0}
numOfHubs = {type = "int", default = 1, desc = "The number of instances that should play the role of the hub"}
numOfIntermediaries = {type = "int", default = 1, desc = "The number of intermediaries(hops) to use in the virtual payment channel"}
numOfPayeePayers = {type = "int", default = 0, desc = "The number of instances that should play the role of the payeepayer"}
numOfPayees = {type = "int", default = 1, desc = "The number of instances that should play the role of the payee"}
numOfPayers = {type = "int", default = 1, desc = "The number of instances that should play the role of the payer"}
paymentTestDuration = {type = "int", default = 10, unit = "seconds"}
