name = "go-nitro"
[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true

[builders."exec:go"]
enabled = true

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:swarm"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
instances = {min = 2, max = 100, default = 5}
name = "create-ledger"

[[testcases]]
instances = {min = 2, max = 100, default = 5}
name = "virtual-payment"

[testcases.params]
concurrentPaymentJobs = {type = "int", desc = "The number of concurrent payment jobs a peer should attempt to maintain", default = 1}
networkJitter = {type = "int", unit = "milliseconds", default = 0}
networkLatency = {type = "int", unit = "milliseconds", default = 0}
numOfHubs = {type = "int", default = 1}
paymentTestDuration = {type = "int", default = 10, unit = "seconds"}

[[testcases]]
instances = {min = 3, max = 100, default = 4}
name = "virtual-payment2"

[testcases.params]
concurrentPaymentJobs = {type = "int", desc = "The number of concurrent payment jobs a peer should attempt to maintain", default = 1}
networkJitter = {type = "int", unit = "milliseconds", default = 0}
networkLatency = {type = "int", unit = "milliseconds", default = 0}
paymentTestDuration = {type = "int", default = 10, unit = "seconds"}