{
 "title": "Engine stats",
 "time": { "from": "2022-09-27T18:31:03.832Z", "to": "2022-09-27T18:31:43.239Z" },
 "templating": {
  "list": [
   {
    "name": "runId",
    "query": " select run,mean from \"diagnostics.go-nitro-testground-virtual-payment.handleMessage.timer\" WHERE $timeFilter "
   }
  ]
 },
 "panels": [
  {
   "title": "Average Function Call durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "executeSideEffects",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "diagnostics.go-nitro-testground-virtual-payment.executeSideEffects.timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" }
     ]
    },
    {
     "alias": "send messages",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "diagnostics.go-nitro-testground-virtual-payment.sendMessages.timer",
     "query": "SELECT mean(\"mean\") FROM \"diagnostics.go-nitro-testground-virtual-payment.sendMessages.timer\" WHERE (\"run\" =~ /^$runId$/) AND $timeFilter GROUP BY time(1s) fill(linear)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" }
     ]
    }
   ]
  },
  {
   "title": "Attempt Progress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_wallet",
     "groupBy": [
      { "params": [ "wallet" ], "type": "tag" }
     ],
     "measurement": "diagnostics.go-nitro-testground-virtual-payment.attemptProgress.timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" }
     ]
    }
   ]
  },
  {
   "title": "Execute Side Effects",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_wallet",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "wallet" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "diagnostics.go-nitro-testground-virtual-payment.executeSideEffects.timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" }
     ]
    }
   ]
  },
  {
   "title": "Handle Message",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_wallet",
     "groupBy": [
      { "params": [ "wallet" ], "type": "tag" }
     ],
     "measurement": "diagnostics.go-nitro-testground-virtual-payment.handleMessage.timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" }
     ]
    }
   ]
  },
  {
   "title": "Queue Sizes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Message queue $tag_wallet",
     "groupBy": [
      { "params": [ "wallet" ], "type": "tag" }
     ],
     "measurement": "diagnostics.go-nitro-testground-virtual-payment.messages_queue.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" }
     ]
    },
    {
     "alias": "Proposal queue $tag_wallet",
     "groupBy": [
      { "params": [ "wallet" ], "type": "tag" }
     ],
     "measurement": "diagnostics.go-nitro-testground-virtual-payment.proposal_queue.gauge",
     "query": "SELECT \"value\" FROM \"diagnostics.go-nitro-testground-virtual-payment.proposal_queue.gauge\" WHERE (\"run\" =~ /^$runId$/) AND $timeFilter GROUP BY \"wallet\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" }
     ]
    },
    {
     "alias": "objective request queue $tag_wallet",
     "groupBy": [
      { "params": [ "wallet" ], "type": "tag" }
     ],
     "measurement": "diagnostics.go-nitro-testground-virtual-payment.api_objective_request_queue.gauge",
     "query": "SELECT \"value\" FROM \"diagnostics.go-nitro-testground-virtual-payment.proposal_queue.gauge\" WHERE (\"run\" =~ /^$runId$/) AND $timeFilter GROUP BY \"wallet\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" }
     ]
    },
    {
     "alias": "payment request queue $tag_wallet",
     "groupBy": [
      { "params": [ "wallet" ], "type": "tag" }
     ],
     "measurement": "diagnostics.go-nitro-testground-virtual-payment.api_payment_request_queue.gauge",
     "query": "SELECT \"value\" FROM \"diagnostics.go-nitro-testground-virtual-payment.proposal_queue.gauge\" WHERE (\"run\" =~ /^$runId$/) AND $timeFilter GROUP BY \"wallet\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" }
     ]
    },
    {
     "alias": "chain queue $tag_wallet",
     "groupBy": [
      { "params": [ "wallet" ], "type": "tag" }
     ],
     "measurement": "diagnostics.go-nitro-testground-virtual-payment.chain_events_queue.gauge",
     "query": "SELECT \"value\" FROM \"diagnostics.go-nitro-testground-virtual-payment.proposal_queue.gauge\" WHERE (\"run\" =~ /^$runId$/) AND $timeFilter GROUP BY \"wallet\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" }
     ]
    }
   ]
  },
  {
   "title": "Handle Objective Request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_wallet",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "wallet" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "diagnostics.go-nitro-testground-virtual-payment.handleObjectiveRequest.timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" }
     ]
    }
   ]
  }
 ]
}