{
 "title": "Message Stats",
 "time": { "from": "2022-09-16T19:21:22.370Z", "to": "2022-09-16T19:24:02.997Z" },
 "templating": {
  "list": [
   {
    "name": "runId",
    "query": "select  run,count FROM \"diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer\" where $timeFilter"
   },
   {
    "name": "jobCount",
    "query": "SELECT concurrentJobs, mean FROM \"diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer\" where run = '$runId'"
   },
   {
    "name": "testDuration",
    "query": "SELECT \"duration\",count FROM \"diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer\" where run='$runId'"
   },
   {
    "name": "hubs",
    "query": "SELECT \"hubs\",count FROM \"diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer\" where run='$runId'"
   },
   {
    "name": "payees",
    "query": "SELECT \"payees\",count FROM \"diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer\" where run='$runId'"
   },
   {
    "name": "jitter",
    "query": "SELECT \"jitter\",count FROM \"diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer\" where run='$runId'"
   },
   {
    "name": "latency",
    "query": "SELECT \"latency\",count FROM \"diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer\" where run='$runId'"
   },
   {
    "name": "payers",
    "query": "SELECT \"payers\",count FROM \"diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer\" where run='$runId'"
   },
   {
    "name": "payeepayers",
    "query": "SELECT \"payeePayers\",count FROM \"diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer\" where run='$runId'"
   }
  ]
 },
 "panels": [
  {
   "title": "Run details",
   "type": "text",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<table style=\"width:100%\"> \n<thead>\n  <tr>\n    <th></th>\n    <th></th>\n  </tr>\n</thead>\n<tbody>\n  <tr>\n    <td>Run Id</td>\n    <td>${runId}</td>\n  </tr>\n  <tr>\n    <td>Client Concurrency</td>\n    <td>${jobCount}</td>\n  </tr>\n  <tr>\n    <td>Payment test duration</td>\n    <td>${testDuration}</td>\n  </tr>\n  <tr>\n    <td>Number of payees</td>\n    <td>${payees}</td>\n  </tr>\n    <tr>\n    <td>Number of payers</td>\n    <td>${payers}</td>\n  </tr>\n     <tr>\n    <td>Number of payee-payers</td>\n    <td>${payeepayers}</td>\n  </tr>\n    <tr>\n    <td>Number of hubs</td>\n    <td>${hubs}</td>\n  </tr>\n      <tr>\n    <td>Latency (ms)</td>\n    <td>${latency}</td>\n  </tr>\n      <tr>\n    <td>Jitter (ms)</td>\n    <td>${jitter}</td>\n  </tr>\n</tbody>\n</table>"
   }
  },
  {
   "title": "Message Size by Sender",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_sender",
     "groupBy": [
      { "params": [ "sender" ], "type": "tag" }
     ],
     "measurement": "diagnostics.go-nitro-virtual-payment.msg_size.gauge",
     "query": "SELECT \"value\" FROM \"diagnostics.go-nitro-virtual-payment.msg_size.gauge\" WHERE (\"run\" =~ /^$runId$/) AND $timeFilter GROUP BY \"sebder\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" }
     ]
    }
   ]
  },
  {
   "title": "Message Size by Receiver",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_receiver",
     "groupBy": [
      { "params": [ "receiver" ], "type": "tag" }
     ],
     "measurement": "diagnostics.go-nitro-virtual-payment.msg_size.gauge",
     "query": "SELECT \"value\" FROM \"diagnostics.go-nitro-virtual-payment.msg_size.gauge\" WHERE (\"run\" =~ /^$runId$/) AND $timeFilter GROUP BY \"receiver\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" }
     ]
    }
   ]
  },
  {
   "title": "Proposal Count by Receiver",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_receiver",
     "groupBy": [
      { "params": [ "receiver" ], "type": "tag" }
     ],
     "measurement": "diagnostics.go-nitro-virtual-payment.msg_proposal_count.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" }
     ]
    }
   ]
  },
  {
   "title": "Proposal Count by Sender",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_sender",
     "groupBy": [
      { "params": [ "sender" ], "type": "tag" }
     ],
     "measurement": "diagnostics.go-nitro-virtual-payment.msg_proposal_count.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" }
     ]
    }
   ]
  },
  {
   "title": "Incoming Message Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 27 },
   "targets": [
    {
     "alias": "Receiver $tag_wallet",
     "groupBy": [
      { "params": [ "wallet" ], "type": "tag" }
     ],
     "measurement": "diagnostics.go-nitro-virtual-payment.messages_queue.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}