{
 "title": "Time to First Payment",
 "time": { "from": "2022-07-04T18:55:21.082Z", "to": "2022-07-04T19:02:08.311Z" },
 "templating": {
  "list": [
   {
    "name": "runId",
    "query": "select  run,count FROM \"diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer\" where $timeFilter"
   },
   {
    "name": "jobCount",
    "query": "SELECT concurrentJobs, mean FROM \"diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer\" where run = '$runId'"
   },
   {
    "name": "testDuration",
    "query": "SELECT \"duration\",count FROM \"diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer\" where run='$runId'"
   },
   {
    "name": "hubs",
    "query": "SELECT \"hubs\",count FROM \"diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer\" where run='$runId'"
   },
   {
    "name": "payees",
    "query": "SELECT \"payees\",count FROM \"diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer\" where run='$runId'"
   },
   {
    "name": "jitter",
    "query": "SELECT \"jitter\",count FROM \"diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer\" where run='$runId'"
   },
   {
    "name": "latency",
    "query": "SELECT \"latency\",count FROM \"diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer\" where run='$runId'"
   },
   {
    "name": "clientAdds",
    "query": "SELECT \"me\",count FROM \"diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer\" where run='$runId'"
   },
   {
    "name": "payers",
    "query": "SELECT \"payers\",count FROM \"diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer\" where run='$runId'"
   },
   {
    "name": "payeepayers",
    "query": "SELECT \"payeePayers\",count FROM \"diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer\" where run='$runId'"
   }
  ]
 },
 "panels": [
  {
   "title": "Run details",
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<table>\n<thead>\n  <tr>\n    <th></th>\n    <th></th>\n  </tr>\n</thead>\n<tbody>\n  <tr>\n    <td>Run Id</td>\n    <td>${runId}</td>\n  </tr>\n  <tr>\n    <td>Client Concurrency</td>\n    <td>${jobCount}</td>\n  </tr>\n  <tr>\n    <td>Payment test duration</td>\n    <td>${testDuration}</td>\n  </tr>\n  <tr>\n    <td>Number of payees</td>\n    <td>${payees}</td>\n  </tr>\n    <tr>\n    <td>Number of payers</td>\n    <td>${payers}</td>\n  </tr>\n     <tr>\n    <td>Number of payee-payers</td>\n    <td>${payeepayers}</td>\n  </tr>\n    <tr>\n    <td>Number of hubs</td>\n    <td>${hubs}</td>\n  </tr>\n      <tr>\n    <td>Latency (ms)</td>\n    <td>${latency}</td>\n  </tr>\n      <tr>\n    <td>Jitter (ms)</td>\n    <td>${jitter}</td>\n  </tr>\n</tbody>\n</table>"
   }
  },
  {
   "title": "Average Function Durations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Handle API",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "diagnostics.go-nitro-virtual-payment.handle_api_event.timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" }
     ]
    },
    {
     "alias": "Handle Message",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "diagnostics.go-nitro-virtual-payment.handle_message.timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" }
     ]
    },
    {
     "alias": "Crank",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "diagnostics.go-nitro-virtual-payment.crank.timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" }
     ]
    }
   ]
  },
  {
   "title": "Average time to first payment",
   "type": "timeseries",
   "description": "The mean time to first payment among ALL clients",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average time to first payment",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" }
     ]
    }
   ]
  },
  {
   "title": "Average duration for hub/provider to open virtual channel",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Hub/Provider $tag_wallet",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "wallet" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "diagnostics.go-nitro-virtual-payment.objective_complete_time.timer",
     "query": "SELECT mean(\"mean\") FROM \"diagnostics.go-nitro-virtual-payment.objective_complete_time.timer\" WHERE (\"run\" =~ /^$runId$/ AND \"type\" = 'VirtualFund' AND \"wallet\" !~ /^${clientAdds:regex}$/) AND $timeFilter GROUP BY time($__interval), \"wallet\" fill(none)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "VirtualFund" },
      { "condition": "AND", "key": "wallet", "operator": "!~", "value": "/^$clientAdds$/" }
     ]
    }
   ]
  },
  {
   "title": "Average time to first payment per client",
   "type": "timeseries",
   "description": "This displays the average time to first payment for each client",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Client $tag_me",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "me" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "diagnostics.go-nitro-virtual-payment.time_to_first_payment.timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runId$/" }
     ]
    }
   ]
  }
 ]
}